#compose para levantar el mongoDB y mongoEspress de la asignatura:
# docker-compose.yml
services:
  mongo:
    image: mongo
    restart: unless-stopped
    volumes:
      - ./data:/data/db
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${USER_DB}
      MONGO_INITDB_ROOT_PASSWORD: ${PASS}

  mongo-express:
    image: mongo-express
    depends_on:
      - mongo
    restart: unless-stopped
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${USER_DB}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${PASS}
      ME_CONFIG_MONGODB_URL: mongodb://${USER_DB}:${PASS}@mongo:27017/
      ME_CONFIG_BASICAUTH: false
